# this is an example of a config file for the base assay which basically keeps track of samples and subjects
# there are some reserved key_value pairs while some of them optional they are reserved. See the documentation for more
# details

assay_name: base
filename: example_base_assay_tables.xlsx
read_fun_params: {} # this is what an empty dict looks like in a yaml

tables:
# these are some examples about how to set up assays, this will include the base assay where we keep cohort/sample
# subject metadata this can be as granular as you wish you just need to keep in mind how the tables are related
  cohorts:
    cohort_id:
      type: str
      index: true
      pk: true
    description:
      type: str
      index: False

  subjects:
    sample_id:
      type: str
      index: true
      pk: true
    tissue:
      type: str
      index: false
  
  subjects_and_cohorts: #this is a linker sample since on subject can belong to more than one cohort
    sample_id:
      type: fk
      fk:
        table: subjects
        column: sample_id
      pk: true
      index: true
    cohort_id:
      type: fk
      fk:
        table: cohorts
        column: cohort_id
      pk: True
      index: True
